version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
      
    
    networks:
      - TeachMall
    
  nacos:
    image: nacos/nacos-server:v2.1.0-slim
    container_name: nacos
    env_file: 
      - "./nacos/custom.env"
    ports: 
      - "8848:8848"
      - "9848:9848" 
      - "9849:9849" 
    restart: always
    volumes:
      - "/root/nacos:/var/lib/nacos"
    networks:
      - TeachMall 
    depends_on:
      - mysql

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: root  
      MINIO_ROOT_PASSWORD: 524628796  
    volumes:
      - ./data:/data
    command: server /data/data1 /data/data2 /data/data3 /data/data4 --console-address ":9001"
    networks:
      - TeachMall
      

  redis:
    image: redis:latest
    container_name: redis
    user: "root"
    ports:
      - "6379:6379"
    networks:
      - TeachMall
    volumes:
      - /redis-data:/data
    command: bash -c "chown -R redis:redis /data && redis-server"
      



  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #     - "8160:8160"
  #     - "80:80"
  #   volumes:
  #     - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  #     - "./nginx/html:/usr/share/nginx/html"

  #   networks:
  #     - TeachMall
#   seata:
#     image: seataio/seata-server:1.5.2
#     container_name: seata
#     ports:
#       - "8099:8099"
#       - "7099:7099"
#     environment:
#       - SEATA_IP=8.138.159.37
#     volumes:
#       - "./seata:/seata-server/resources"
#     privileged: true
#     networks:
#       - hm-net
#     restart: always
      

  mq:
    image: rabbitmq:3.8-management
    container_name: mq
    hostname: mq
    environment:
      RABBITMQ_DEFAULT_USER: teachmall
      RABBITMQ_DEFAULT_PASS: 123
    volumes:
      - mq-plugins:/plugins
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - TeachMall
    deploy:
      restart_policy:
        condition: on-failure
  # ping:
  #   image: alpine:latest
  #   container_name: ping
  #   tty: true
  #   stdin_open: true
  #   entrypoint: /bin/sh
  #   command: -c "apk update && apk add --no-cache curl iputils && while true; do sleep 3600; done"
  #   networks:
  #     - TeachMall
    

        
volumes:
  mq-plugins:
    driver: local

      
networks:
  TeachMall:
    name: TeachMall
    driver: bridge